const fs = require('fs');
const file = 'static/js/map-layers.js';
let content = fs.readFileSync(file, 'utf8');

// Find map.on('click' ... and replace it

const regexClick = /map\.on\('click', async function\(e\) \{[\s\S]*?\n        \}\);\n/m;
if (!regexClick.test(content)) {
    console.log("Could not find click event");
    process.exit(1);
}

const newClickEvent = `// The Master Unified Click Event Listener
        map.on('click', async function(e) {
            if (window.currentTool && (window.currentTool === 'ruler' || window.currentTool === 'circle')) {
                return;
            }

            const lat = e.latlng.lat;
            const lng = e.latlng.lng;
            const clickPoint = turf.point([lng, lat]);
            const estimates = calculatePassEstimates(lng);

            // We will build one giant, scrollable HTML string
            let popupHTML = \`<div style="min-width: 250px; max-width: 320px; max-height: 400px; overflow-y: auto; padding-right: 5px;">\`;

            // --- 1. Location Intelligence (Always shows) ---
            popupHTML += \`
                <h3 style="margin: 0 0 8px 0; border-bottom: 1px solid #475569; padding-bottom: 4px;">Location Intelligence</h3>
                <p style="margin: 4px 0; font-size: 0.85rem;"><b>Lat:</b> \${lat.toFixed(4)}<br><b>Lng:</b> \${lng.toFixed(4)}</p>

                <div id="osmGeoLookup" style="margin: 8px 0; padding: 6px; background: rgba(0,0,0,0.2); border-radius: 4px; font-size: 0.85rem; border-left: 2px solid #3b82f6;">
                    <em style="color: #94a3b8;">Scanning location data...</em>
                </div>

                <h4 style="margin: 10px 0 4px 0; color: #93c5fd;">🛰️ Estimated Daily Passes</h4>
                <ul style="margin: 0; padding-left: 20px; font-size: 0.85rem;">
                    <li><b>Sentinel-2:</b> ~\${estimates.sentinel}</li>
                    <li><b>FIRMS (VIIRS):</b> ~\${estimates.viirs}</li>
                </ul>
                <em style="font-size: 0.75rem; color: #94a3b8;">*Sun-synchronous estimates based on longitude. High latitudes (e.g. Ukraine) receive multiple overlapping swath looks.</em>

                <div id="wmsInfo" style="margin-top: 10px; padding-top: 10px; border-top: 1px solid #475569; display: none;">
                    <h4 style="margin: 0 0 4px 0; color: #22c55e;">📸 Sentinel Image Data</h4>
                    <div id="wmsLoading">Querying Copernicus...</div>
                </div>
            \`;

            // --- 2. KML Data & Metadata Extraction ---
            let kmlHitsHTML = '';
            for (const filename in activeKMLGeoJSON) {
                // Only drill down if the layer is visibly checked on the map
                if (activeLayers[filename] && map.hasLayer(activeLayers[filename])) {
                    turf.featureEach(activeKMLGeoJSON[filename], function (currentFeature) {
                        let isHit = false;

                        // Mathematical intersection based on geometry type
                        if (currentFeature.geometry.type === 'Polygon' || currentFeature.geometry.type === 'MultiPolygon') {
                            isHit = turf.booleanPointInPolygon(clickPoint, currentFeature);
                        } else if (currentFeature.geometry.type === 'Point') {
                            const dist = turf.distance(clickPoint, currentFeature, {units: 'meters'});
                            isHit = dist < 500; // 500m hit tolerance for points
                        } else if (currentFeature.geometry.type === 'LineString' || currentFeature.geometry.type === 'MultiLineString') {
                            const dist = turf.pointToLineDistance(clickPoint, currentFeature, {units: 'meters'});
                            isHit = dist < 500; // 500m hit tolerance for lines
                        }

                        if (isHit) {
                            kmlHitsHTML += \`<div style="margin-top: 12px; border-top: 1px solid #475569; padding-top: 8px;">\`;
                            kmlHitsHTML += \`<h4 style="margin: 0 0 6px 0; color: #facc15;">📁 \${filename}</h4>\`;

                            // The Magic Loop: Extracts ALL metadata dynamically
                            if (currentFeature.properties) {
                                for (const key in currentFeature.properties) {
                                    // Ignore useless internal styling keys generated by toGeoJSON
                                    if (key !== 'styleUrl' && key !== 'styleHash' && key !== 'styleMapHash') {
                                        const val = currentFeature.properties[key];
                                        // Format links cleanly if they exist
                                        if (val) {
                                            const displayVal = String(val).startsWith('http') ? \`<a href="\${val}" target="_blank" style="color:#3b82f6;">Link</a>\` : val;
                                            kmlHitsHTML += \`<div style="font-size: 0.85rem; margin-bottom: 3px; word-wrap: break-word;"><b>\${key}:</b> \${displayVal}</div>\`;
                                        }
                                    }
                                }
                            }
                            kmlHitsHTML += \`</div>\`;
                        }
                    });
                }
            }
            if (kmlHitsHTML) popupHTML += kmlHitsHTML;

            // --- 3. FIRMS Data Drill-down ---
            if (map.hasLayer(firmsVectorGroup)) {
                let firmsHitsHTML = '';
                currentFirmsData.forEach(fire => {
                    const firePt = turf.point([parseFloat(fire.longitude), parseFloat(fire.latitude)]);
                    const dist = turf.distance(clickPoint, firePt, {units: 'meters'});

                    // If click is within 1km of a fire center, count it as a hit
                    if (dist < 1000) {
                        const timeStr = fire.acq_time.padStart(4, '0');
                        firmsHitsHTML += \`
                            <div style="margin-top: 12px; border-top: 1px solid #475569; padding-top: 8px;">
                                <h4 style="margin: 0 0 4px 0; color: #ef4444;">🔥 Thermal Anomaly</h4>
                                <div style="font-size: 0.85rem;">
                                    <b>Detected:</b> \${fire.acq_date} at \${timeStr} UTC<br>
                                    <b>Confidence:</b> \${fire.confidence}
                                </div>
                            </div>
                        \`;
                    }
                });
                if (firmsHitsHTML) popupHTML += firmsHitsHTML;
            }

            // Close the master container and trigger Leaflet
            popupHTML += \`</div>\`;

            const popup = L.popup()
                .setLatLng(e.latlng)
                .setContent(popupHTML)
                .openOn(map);

            // Fire the reverse geocoding API in the background
            if (typeof reverseGeocodeLocation === 'function') {
                reverseGeocodeLocation(lat, lng).then(resultHTML => {
                    const lookupDiv = document.getElementById('osmGeoLookup');
                    if (lookupDiv) {
                        lookupDiv.innerHTML = resultHTML;
                    }
                });
            }

            // If the Sentinel layer is currently active on the map, fetch the image date
            if (map.hasLayer(layers.sentinelLive) && map.getZoom() > 9) {
                const wmsInfo = document.getElementById('wmsInfo');
                if (wmsInfo) wmsInfo.style.display = 'block';

                const url = getFeatureInfoUrl(map, layers.sentinelLive, e.latlng);

                try {
                    const response = await fetch(url);
                    if (!response.ok) throw new Error("Network response was not ok");

                    const data = await response.json();

                    if (data && data.features && data.features.length > 0) {
                        // Sentinel Hub returns the date in the properties object
                        const date = data.features[0].properties.date || "Date unknown";
                        const time = data.features[0].properties.time || "";
                        const wmsLoading = document.getElementById('wmsLoading');
                        if (wmsLoading) {
                            wmsLoading.innerHTML = \`
                                <b>Acquired:</b> \${date} \${time} UTC
                            \`;
                        }
                    } else {
                        const wmsLoading = document.getElementById('wmsLoading');
                        if (wmsLoading) wmsLoading.innerHTML = \`<em style="color: #94a3b8;">No image metadata found for this pixel.</em>\`;
                    }
                } catch (error) {
                    console.error("WMS GetFeatureInfo Error:", error);
                    const wmsLoading = document.getElementById('wmsLoading');
                    if (wmsLoading) wmsLoading.innerHTML = \`<em style="color: #ef4444;">Failed to retrieve image data.</em>\`;
                }
            }
        });
`;

content = content.replace(regexClick, newClickEvent);
fs.writeFileSync(file, content);
console.log("Replaced click event");
